minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.14.22
meteor_version=0.5.1
mod_version=1.1.0
maven_group=com.wgf
archives_base_name=wgf-firework-autofarm

# FIX CRASH JVM:
# -Xms = -Xmx per evitare allocazioni dinamiche
# UseG1GC per gestire meglio la memoria su Windows
# MaxMetaspaceSize aumentato perché Loom 1.1.14 lo consuma molto durante il remapping
org.gradle.jvmargs=-Xmx2G -Xms2G -XX:MaxMetaspaceSize=1G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=false
